env: 
  DIR=$PWD
  SWIFT_VERSION=swift-3.1.1-RELEASE

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: cpp
      env: PATH="${PWD}/${SWIFT_VERSION}-ubuntu14.04/usr/bin/:${PATH}"
    - os: osx
      osx_image: xcode8.3
      language: objective-c
      sudo: required
      
script:
  - swift build
  - swift test
  
before_install:
  - chmod ugo+x ./InstallSwift.sh
  - ./InstallSwift.sh
  
notifications:
  email:
    on_success: never
    on_failure: change
